[package]
name = "find_file_duplicates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.8"
data-encoding = "2.5.0"
log = "0.4"
walkdir = "2.5.0"